# Generated by Django 4.1 on 2022-09-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000, verbose_name='Задача')),
                ('status', models.CharField(max_length=12, verbose_name='Статус')),
                ('deadline_date', models.DateField(blank=True, verbose_name='Срок выполнения')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
