# Generated by Django 4.1 on 2022-09-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0005_task_task_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
